seed: 42
saved_dir: ./saved
exp_name: PAN_Swin_Alldata
val_every: 1

model:
  name: PAN
  params:
    encoder_name: swin_encoder
    encoder_weights: imagenet
    encoder_output_stride: 32
    in_channels: 3
    classes: 11

dataset_path: '../input/data'
train_path: ../input/data/train_all.json
val_path: ../input/data/split/valid_0.json

train_dataloader:
  params:
    batch_size: 12
    shuffle: true
    num_workers: 4
    drop_last: true

valid_dataloader:
  params:
    batch_size: 12
    shuffle: true
    num_workers: 4

transforms:
  name: all_transform

epochs: 40

criterion: 
  name: jaccard_soft_ce

optimizer:
  name: AdamW
  params:
    lr: 0.0001 # 1e4
    weight_decay: 0.00001 # 1e5

scheduler:
  name: OneCycleLR
  params:
    max_lr: 0.0001 # 1e4
    pct_start: 0.05
    steps_per_epoch: 1
    epochs: 40